export const pizzaData = [
  {
    name: "Focaccia",
    ingredients: "Bread with italian olive oil and rosemary",
    price: 6,
    photoName: "pizzas/focaccia.jpg",
    stock: 2,
    soldOut: false,
    id: 123,
  },
  {
    name: "Pizza Margherita",
    ingredients: "Tomato and mozarella",
    price: 10,
    stock: 1,
    photoName: "pizzas/margherita.jpg",
    soldOut: false,
    id: 234,
  },
  {
    name: "Pizza Spinaci",
    ingredients: "Tomato, mozarella, spinach, and ricotta cheese",
    price: 12,
    stock: 0,
    photoName: "pizzas/spinaci.jpg",
    soldOut: false,
    id: 456,
  },
  {
    name: "Pizza Funghi",
    ingredients: "Tomato, mozarella, mushrooms, and onion",
    price: 12,
    photoName: "pizzas/funghi.jpg",
    soldOut: false,
    stock: 0,
    id: 678,
  },
  {
    name: "Pizza Salamino",
    ingredients: "Tomato, mozarella, and pepperoni",
    price: 15,
    photoName: "pizzas/salamino.jpg",
    soldOut: true,
    stock: 5,
    id: 789,
  },
  {
    name: "Pizza Prosciutto",
    ingredients: "Tomato, mozarella, ham, aragula, and burrata cheese",
    price: 18,
    photoName: "pizzas/prosciutto.jpg",
    soldOut: false,
    stock: 12,
    id: 890,
  },
];

export const beerData = [
  {
    name: "Bud",
    price: 10,
    ingredients: "Filtered beer, available on draft and in bottles and cans",
    photoName: "beers/Bud.jpg",
    soldOut: false,
    id: 222,
  },
  {
    name: "BudLight",
    price: 12,
    ingredients: "premium beer with incredible drinkability",
    photoName: "beers/BudLight.jpg",
    stock: true,
    soldOut: false,
    id: 111,
  },
  {
    name: "Corona",
    price: 8,
    ingredients: "easy-to-enjoy Mexican beer ",
    photoName: "beers/Corona.jpg",
    stock: true,
    soldOut: false,
    id: 333,
  },
  {
    name: "Heineken",
    price: 15,
    ingredients: "full-bodied premium lager with deep golden colour",
    photoName: "beers/Heineken.jpg",
    stock: true,
    soldOut: false,
    id: 444,
  },
  {
    name: "Huerca",
    price: 6,
    ingredients: "100% Artesanal, 100% Mexicana",
    photoName: "beers/Huerca.jpg",
    stock: true,
    soldOut: false,
    id: 555,
  },
  {
    name: "Modelo",
    price: 9,
    ingredients: "A light, bubbly Pilsner-style beer",
    photoName: "beers/Modelo.jpg",
    stock: false,
    soldOut: false,
    id: 666,
  },
  {
    name: "Aegis",
    price: 10,
    ingredients: "Traditional Norway beer",
    photoName: "beers/Aegis.jpg",
    stock: true,
    soldOut: false,
    id: 777,
  },
  {
    name: "Kalık",
    price: 10.5,
    ingredients: "a golden, bold, full-bodied lager of premium quality ",
    photoName: "beers/Kalık.jpg",
    stock: true,
    soldOut: true,
    id: 888,
  },
];
